[phases.setup]
nixPkgs = ["python310", "gcc"]

[phases.install]
cmds = ["python3.10 -m venv venv", ". venv/bin/activate", "pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT"
