[phases.setup]
nixPkgs = ['python3', 'gcc']

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "/opt/venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/gunicorn -w 4 -b 0.0.0.0:$PORT app:app"
